volumes:
  web-data: /mnt/copo-data/prod_copo/web-data
  logs-data: /mnt/copo-data/prod_copo/logs-data
  b2drop-permits: /app/copo/ERGA/ERGA
  mongo-backup: /mnt/copo-data/prod_copo/mongo-data
  postgres-backup: /mnt/copo-data/prod_copo/postgres-data
  minio-data1: /mnt/copo-data/prod_copo/minio-data1-service
  minio-data2: /mnt/copo-data/prod_copo/minio-data2-service
