$ANSIBLE_VAULT;1.1;AES256
65363839333263656539343737643435346636356538633765623136353261666433393065396465
3364666565646662346433396430343464633131633837350a363130326438343161316532373132
33383632656463306262376439313133636666613639363465653231343437323234383465323530
6537323236623035300a653337346564373035303438616433376466386431663530333937356634
63633838393639376430346335326130346162343465356435653366646166653734353836356632
62613238663166616138623938333738356530376531636664313730373762313839643230613631
30663338343134383932373539633465393663376564656338353262323730376334626439626566
37383361633431373565636232396661313462353834636465333238363361393461316431386634
30353061303636393865306432313139616531653831336562376339396330626666313438656130
3231663230343537613462313832623761316661633333623063
