volumes:
  web-data: /mnt/copo-data/demo_copo/web-data
  logs-data: /mnt/copo-data/demo_copo/logs-data
  minio-data1: /mnt/copo-data/demo_copo/minio-data1-frontend
  minio-data2: /mnt/copo-data/demo_copo/minio-data2-frontend
